sudo: false
language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python companystatistics/manage.py migrate
  - coverage run companystatistics/manage.py test
notifications:
  email: false
after_success:
  coveralls