sudo: false
language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py migrate
  - coverage run manage.py test
notifications:
  email: false
after_success:
  coveralls