# Generated by Django 2.2.11 on 2020-04-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='owner',
            new_name='stat_title',
        ),
    ]
