# Generated by Django 2.2.11 on 2020-04-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_app', '0002_auto_20200421_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='stat_title',
            new_name='owner',
        ),
    ]
